apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-wtxj
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0010-tenant/tkrw-pr712-0075-0010-app/devfile-sample-wtxj@sha256:657371b0a9cafe3781a4f8e81017da92622b01e052c69a89f7cd018b54f27a2b
        name: my-nodejs
        resources: {}
status: {}
